Web_ecomerce2/Web_ecomerce2/Controllers/DanhMucController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web_ecomerce2.Model;

namespace Web_ecomerce2.Content
{
    public class DanhMucController : Controller
    {
      //  public object Model1 { get; private set; }
        public ActionResult productList(string iddanhmuc)
        {
            e_comerceEntities db = new e_comerceEntities();
            List<SanPham> prolist = (from q in db.SanPhams where q.IdDanhMuc == iddanhmuc select q).ToList();
            return View(prolist);
        }

        // GET: DanhMuc
        public ActionResult LoadDanhMuc()
        {
            e_comerceEntities db = new e_comerceEntities();
            List<DanhMuc> dmList = db.DanhMucs.ToList();
            return PartialView(dmList);

       
        }
    }
}

Web_ecomerce2/Web_ecomerce2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web_ecomerce2.Model;

namespace Web_ecomerce2.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            e_comerceEntities db = new e_comerceEntities();
            List<SanPham> name = db.SanPhams.ToList();
            return View(name);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Web_ecomerce2/Web_ecomerce2/Controllers/chitietController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web_ecomerce2.Model;
namespace Web_ecomerce2.Controllers
{
    public class chitietController : Controller
    {
        // GET: chitiet
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult loadchitiet(int id)
        {
            e_comerceEntities db = new e_comerceEntities();
            List<SanPham> detail = (from q in db.SanPhams where q.MaSP == id select q).ToList();
            return View(detail);
        }

    }
}

Web_ecomerce2/Web_ecomerce2/Controllers/userController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using System.Web.Security;
using System.Web.Mvc;
using Web_ecomerce2.Model;
namespace Web_ecomerce2.Controllers
{
    public class userController : Controller
    {
        e_comerceEntities db = new e_comerceEntities();
        public bool checkUser(string name, string pass)
        {
            if (db.KhachHangs.Where(m => m.Email == name && m.MatKhau == pass).Count() > 0)
            {
                return true;
            }
            return false;
        }
        // GET: user

        public ActionResult Index()
        {
            return View();
        }
      
        public ActionResult LogIn()
        {
            return View();
        }
        public ActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Register(KhachHang user)
        {
            if (ModelState.IsValid)
            {
                string password2 = MaHoa.MD5Hash(user.MatKhau);
                //xét email ko trùng
                if (ModelState.IsValid)
                {
                    if (db.KhachHangs.Where(m => m.Email.Equals(user.Email)).Count()==0)
                    {
                        KhachHang objKH = new KhachHang();
                        objKH.TenKH = user.TenKH;
                        objKH.DiaChi = user.DiaChi;
                        objKH.SDT = user.SDT;
                        objKH.Email = user.Email;
                        objKH.MatKhau = password2;
                        db.KhachHangs.Add(objKH);
                        //lưu vào csdl

                        db.SaveChanges();

                        return RedirectToAction("Login", "user");
                    }
                    else
                    // trùng email
                    {
                        ModelState.AddModelError("Email", "Email đã tồn tại !");
                    }
                }
                
            }
                return View("Register");
            
        }

        public ActionResult LogOff()
        {
            FormsAuthentication.SignOut(); //xoa cookie

            //WebSecurity.Logout();
            Session["Name"] = null;
            return RedirectToAction("LogIn", "User");
        }

        private bool checkUserLogin(LoginModel meomeo)
        {
            string meo = MaHoa.MD5Hash(meomeo.passWord);
            if (db.KhachHangs.Where(m => m.SDT == meomeo.userName && m.MatKhau.Equals(meo)).Count() == 1 || db.KhachHangs.Where(m => m.Email == meomeo.userName && m.MatKhau.Equals(meo)).Count() == 1)
            {
                return true;
            }
            return false;
        }

        [HttpPost]
        public ActionResult LogIn(LoginModel user1)
        {
            //dùng để clear lỗi của ràng buộc nhập tên kh.
            //ModelState.Where(m => m.Key == "TenKH").FirstOrDefault().Value.Errors.Clear();
            ///ModelState.Where(m => m.Key == "DiaChi").FirstOrDefault().Value.Errors.Clear();
            if (ModelState.IsValid)
            {
               // string pass = MaHoa.MD5Hash(user1.passWord);
                //ModelState.Where(m => m.Key == "tenkh").FirstOrDefault().Value.Errors.Clear();
                if (checkUserLogin(user1))
                {
                    KhachHang kh = db.KhachHangs.Where(m => m.SDT == user1.userName || m.Email == user1.userName).FirstOrDefault();
                    //gọi hàm GetRolesForUser(string username) 
                    //trong fie CustomRoleProvider.cs) 
                    //nó sẽ chuyền giá trị username để lấy quyền.
                    FormsAuthentication.SetAuthCookie(kh.TenKH, true);

                    Session["Name"] = kh.TenKH.ToString();
                    return RedirectToAction("Index", "Home");
                }
            }
            ViewBag.ErrorMessage = "SAI TÊN ĐĂNG NHẬP HOẶC MẬT KHẨU ? Bạn chưa có tài khoản? Bấm Đăng ký";
            return View();

        }


    }
}

Web_ecomerce2/Web_ecomerce2/Views/DanhMuc/LoadDanhMuc.cshtml
@model List<Web_ecomerce2.Model.DanhMuc>
<div class="sidebar_section">
  
    <ul id="list">
        @foreach (var dm in Model)
        {
            <li >@Html.ActionLink(dm.TenDanhMuc, "productlist", "danhmuc", new { iddanhmuc = dm.IdDanhMuc }, null)</li>
        }
    </ul>
</div>

Web_ecomerce2/Web_ecomerce2/Views/DanhMuc/productList.cshtml
@model List<Web_ecomerce2.Model.SanPham>


<div id="items">
    @for (int i = 0; i < Model.Count(); i++)
    {
        if (i % 3 == 2)
        {
            <div class="item">
                <img src="~/@Model[i].HA" alt="" width="202" height="173" /><br />
                <span>@Model[i].Gia</span>
                <a href="@Url.Action("loadchitiet","chitiet", new { id = @Model[i].MaSP },null)" class="view">View</a>
                <a href="#" class="buy">Buy this Product</a>
            </div>

        }
        else
        {
            <div class="item">
                <img src="~/@Model[i].HA" alt="" width="202" height="173" /><br />
                <span>@Model[i].Gia</span>
                <a href="@Url.Action("loadchitiet","chitiet", new { id = @Model[i].MaSP },null)" class="view">View</a>
                <a href="#" class="buy">Buy this Product</a>
            </div>
        }
    }
</div>

Web_ecomerce2/Web_ecomerce2/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Web_ecomerce2/Web_ecomerce2/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Web_ecomerce2/Web_ecomerce2/Views/Home/Index.cshtml
@model List<Web_ecomerce2.Model.SanPham>


<div id="items">
    @for (int i = 0; i < Model.Count(); i++)
    {
        if (i % 3 == 2)
        {
            <div class="item">
                <img src="@Model[i].HA" alt="" width="202" height="173" /><br />
                <span>@Model[i].Gia</span>
                <a href="@Url.Action("loadchitiet","chitiet", new { id = @Model[i].MaSP },null)" class="view">View</a>
                <a href="#" class="buy">Buy this Product</a>
            </div>

        }
        else
        {
            <div class="item">
                <img src="@Model[i].HA" alt="" width="202" height="173" /><br />
                <span>@Model[i].Gia</span>
                <a href="@Url.Action("loadchitiet","chitiet", new { id = @Model[i].MaSP },null)" class="view">View</a>
                <a href="#" class="buy">Buy this Product</a>
            </div>
        }
    }

    @*<div class="item">
            <img src="~/images//item1.jpg" alt="" width="202" height="173" /><br />
            <span>$99</span><a href="index2.html" class="view">View</a><a href="#" class="buy">Buy this Product</a>
        </div>
        <div class="item">
            <img src="~/images//item2.jpg" alt="" width="202" height="173" /><br />
            <span>$150</span><a href="index2.html" class="view">View</a><a href="#" class="buy">Buy this Product</a>
        </div>
        <div class="item">
            <img src="~/images//item3.jpg" alt="" width="202" height="173" /><br />
            <span>$250</span><a href="index2.html" class="view">View</a><a href="#" class="buy">Buy this Product</a>
        </div>
        <div class="item">
            <img src="~/images//item4.jpg" alt="" width="202" height="173" /><br />
            <span>$120</span><a href="index2.html" class="view">View</a><a href="#" class="buy">Buy this Product</a>
        </div>
        <div class="item">
            <img src="~/images//item5.jpg" alt="" width="202" height="173" /><br />
            <span>$1255</span><a href="index2.html" class="view">View</a><a href="#" class="buy">Buy this Product</a>
        </div>
        <div class="item">
            <img src="~/images//item6.jpg" alt="" width="202" height="173" /><br />
            <span>$215</span><a href="index2.html" class="view">View</a><a href="#" class="buy">Buy this Product</a>
        </div>*@
</div>

Web_ecomerce2/Web_ecomerce2/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
          "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>Furniture Shop</title>
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
    <link rel="stylesheet" type="text/css" href="~/style.css" />
</head>

<body>
    <div id="header">
        <div id="header_inside">
            <img src="~/images//header.jpg"  alt="setalpm" width="999" height="222" border="0" usemap="#Map" /><br />
            <ul id="menu">
                <li><a href="http://localhost:2847/" class="but1_active">Home Page</a></li>
                <li><a href="index2.html" class="but2">About Us</a></li>
                <li><a href="index2.html" class="but3">News &amp; Events</a></li>
                <li><a href="index2.html" class="but4">Services</a></li>
                 <li>
                    @if (Session["Name"] != null)
                    {
                        <a>Welcome @Session["Name"].ToString()</a><i>@Html.ActionLink(" LogOut", "LogOff", "User")</i>

                    }
                    else
                    {
                    <li><a href="~/User/LogIn"> Login</a></li>
                    }
                </li>
                <li><a href="index2.html" class="but6">Contacts</a></li>
            </ul>
        </div>
    </div>
    <div id="wrapper">
        <div id="content_inside">
            <div id="sidebar">
                <img src="~/images//title1.gif" alt="" width="174" height="30" /><br />
               




                @Html.Action("LoadDanhMuc","DanhMuc")







            </div>
            <div id="main_block">
                <div class="about">
                    <img src="~/images//title2.gif" alt="" width="191" height="30" /><br />
                    <p>Illum secundum exerci erat plaga illum, enim, venio. Tamen causa ut diam torqueo sagaciter inhibeo si quae exerci lobortis. Appellatio vel hos autem, ludus luptatum mauris ratis jugis interdico. Gilvus consequat abico demoveo lenis validus typicus ut commodo. Consequat, eu voco cui eros, euismod quis illum, commodo. Nibh valde tincidunt ex quae ratis meus neo aliquam. Appellatio vel hos autem, ludus luptatum mauris ratis jugis interdico. Gilvus consequat abico demoveo lenis validus typicus ut commodo. Consequat, eu voco cui eros, euismod quis illum, commodo. Nibh valde tincidunt ex quae ratis meus neo aliquam. </p>
                    <a href="#">more info</a>
                </div>
                <div class="news">
                    <img src="~/images//title3.gif" alt="" width="69" height="30" /><br />
                    <p>Illum secundum exerci erat plaga illum, enim, venio. Tamen causa ut diam torqueo sagaciter inhibeo si quae exerci lobortis. Appellatio vel hos autem, ludus luptatum mauris ratis jugis interdico. Gilvus consequat abico demoveo lenis validus typicus ut commodo. Consequat, eu voco cui eros, euismod quis illum, commodo. </p>
                </div>
                @RenderBody();

            </div>
        </div>
    </div>
    <div id="footer">
        <div id="footer_inside">
            <ul class="footer_menu">
                <li><a href="index.html">Home Page</a>|</li>
                <li><a href="index2.html">About Us</a>|</li>
                <li><a href="index2.html">News &amp; Events</a>|</li>
                <li><a href="index2.html">Services</a>|</li>
                <li><a href="index2.html">My Account</a>|</li>
                <li><a href="index2.html">Contacts</a></li>
            </ul><br /><br />
            <p>Copyright &copy;. All rights reserved. Design by <a href="http://www.bestfreetemplates.info" target="_blank" title="Best Free Templates">BFT</a></p>
        </div>
    </div>
    <map name="Map">
        <area shape="rect" coords="78,45,312,119" href="index.html">
        <area shape="poly" coords="670,87,719,78,727,123,677,130" href="#">
        <area shape="poly" coords="776,124,818,152,793,189,751,160" href="#">
        <area shape="poly" coords="834,52,885,61,878,105,828,96" href="#">
    </map>
</body>
</html>

Web_ecomerce2/Web_ecomerce2/Views/chitiet/loadchitiet.cshtml
@model List<Web_ecomerce2.Model.SanPham>
@{
    ViewBag.Title = "loadchitiet";
}

<h2>loadchitiet</h2>
<div class="item">
    <h1 >@Model[0].TenSP</h1><br/>
    <img src="~/@Model[0].HA" alt="" width="202" height="173" /><br />
    <span style="color:red">@Model[0].Gia</span>
    <span style="color:red">@Model[0].SL</span>
    <a href="#" class="buy">Buy this Product</a>
</div>

Web_ecomerce2/Web_ecomerce2/Views/user/LogIn.cshtml
@model Web_ecomerce2.Model.LoginModel
@{
    ViewBag.Title = "LogIn";
}
<h2 style="margin-top:200px ; margin-left:350px">ĐĂNG NHẬP</h2><br />
@using (Html.BeginForm("Login", "User", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4 style=" margin-left:250px">VUI LÒNG ĐIỀN VÀO THÔNG TIN ĐỂ ĐĂNG NHẬP.</h4><br />
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group" style=" margin-left:300px">
        @Html.LabelFor(m => m.userName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.userName, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.userName, "", new { @class = "text-danger" })
        </div>
    </div>
    <br />
    <div class="form-group" style=" margin-left:300px">
        @Html.LabelFor(m => m.passWord, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.passWord, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.passWord, "", new { @class = "text-danger" })
        </div>
    </div>
    @*<div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <div class="checkbox">
                    @Html.CheckBoxFor(m => m.RememberMe)
                    @Html.LabelFor(m => m.RememberMe)
                </div>
            </div>
        </div>*@
    <br />
    <div class="form-group" style=" margin-left:350px">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Đăng nhập" class="btn btn-default" />
            <a> @Html.ActionLink("Đăng Ký", "Register", "user")</a>
        </div>
    </div>
    <br />
    if (ViewBag.ErrorMessage != null)
    {
        <div style=" margin-left:250px">
            <span style="color:red">
                @ViewBag.ErrorMessage<br />
                <a style=" margin-left:110px"> @Html.ActionLink("Đăng Ký", "Register", "user")</a> 
            </span>
        </div>

    }

    @* Enable this once you have account confirmation enabled for password reset functionality
        <p>
            @Html.ActionLink("Forgot your password?", "ForgotPassword")
        </p>*@
}

Web_ecomerce2/Web_ecomerce2/Views/user/Register.cshtml
@model Web_ecomerce2.Model.KhachHang
@{
    ViewBag.Title = "Register";

}

<h2 style="margin-top:200px ; margin-left:350px">ĐĂNG KÝ</h2><br />
@using (Html.BeginForm("Register", "User", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{

    @Html.AntiForgeryToken()
    <h4 style=" margin-left:250px">VUI LÒNG ĐIỀN VÀO THÔNG TIN ĐỂ ĐĂNG KÝ.</h4><br />

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group" style=" margin-left:300px">
        @Html.LabelFor(m => m.TenKH, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.TenKH, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.TenKH, "", new { @class = "text-danger" })
        </div>
    </div>
    <br />

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group" style=" margin-left:300px">
        @Html.LabelFor(m => m.DiaChi, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.DiaChi, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.DiaChi, "", new { @class = "text-danger" })
        </div>
    </div>
    <br />

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group" style=" margin-left:300px">
        @Html.LabelFor(m => m.SDT, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.SDT, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.SDT, "", new { @class = "text-danger" })
        </div>
    </div>
    <br />

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group" style=" margin-left:300px">
        @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
        </div>
    </div>
    <br />

    <div class="form-group" style=" margin-left:300px">
        @Html.LabelFor(m => m.MatKhau, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.MatKhau, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.MatKhau, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group" style=" margin-left:350px">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Đăng ký" />
        </div>
    </div>
    @*<div class="form-group">
            @Html.LabelFor(m => m.Username, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Username, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Address, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Address, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Phone, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Phone, new { @class = "form-control" })
            </div>
        </div>*@

}